# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "4fd98d6fe8bcbc05cb6228f8614f91f1"
application_url = "https://exceptional-denver-polo-loose.trycloudflare.com"
embedded = true
name = "Demo-billing"
handle = "demo-billing-1"

[webhooks]
api_version = "2024-10"

  [[webhooks.subscriptions]]
  topics = [ "app/uninstalled" ]
  uri = "/webhooks/app/uninstalled"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://exceptional-denver-polo-loose.trycloudflare.com/auth/callback",
  "https://exceptional-denver-polo-loose.trycloudflare.com/auth/shopify/callback",
  "https://exceptional-denver-polo-loose.trycloudflare.com/api/auth/callback"
]

[pos]
embedded = false

[build]
dev_store_url = "hungstore-vn.myshopify.com"
automatically_update_urls_on_dev = true
